"""
run_offline.py — Offline UKF Validation with Synthetic MATLAB Data

Loads ground truth and synthetic IMU data generated by the MATLAB
scripts, runs the UKF filter over the entire dataset, and produces
publication-quality comparison plots.

Usage:
    python run_offline.py

Expected data files (in ../matlab/ relative to this script):
    - ground_truth.csv:  time, q0, q1, q2, q3, wx, wy, wz, ax, ay, az
    - synthetic_imu.csv: time, ax1, ay1, az1, gx1, gy1, gz1, ..., gz3

Output:
    - results.png: 4-subplot comparison figure
    - Console: RMSE values for each Euler angle

Author: Senior Project — Multi-IMU UKF Sensor Fusion
"""

import os
import sys
import time
import numpy as np
import matplotlib.pyplot as plt

# Add the current directory to the path for local imports
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from quaternion_utils import quat_to_euler
from models import process_model, measurement_model, SIGMA_ACCEL, SIGMA_GYRO
from ukf import UKF


# ────────────────────────────────────────────────────────────────────
# Configuration
# ────────────────────────────────────────────────────────────────────

# Sampling parameters (must match MATLAB)
DT = 0.005  # 200 Hz → 5 ms timestep

# UKF tuning parameters
UKF_ALPHA = 1e-3
UKF_BETA = 2
UKF_KAPPA = 0


def setup_plot_style():
    """Set up matplotlib for publication-quality plots."""
    # Try modern seaborn style, fall back gracefully
    style_options = [
        'seaborn-v0_8-whitegrid',
        'seaborn-whitegrid',
        'ggplot',
        'default'
    ]
    for style in style_options:
        try:
            plt.style.use(style)
            break
        except OSError:
            continue

    # Override some defaults for a cleaner look
    plt.rcParams.update({
        'figure.dpi': 150,
        'font.size': 10,
        'axes.titlesize': 12,
        'axes.labelsize': 10,
        'legend.fontsize': 8,
        'lines.linewidth': 1.2,
        'figure.figsize': (14, 10),
    })


def load_data(script_dir):
    """Load ground truth and synthetic IMU CSV files.

    Parameters
    ----------
    script_dir : str
        Directory containing this script (python/).

    Returns
    -------
    gt_data : ndarray
        Ground truth: [time, q0, q1, q2, q3, wx, wy, wz, ax, ay, az]
    imu_data : ndarray
        IMU measurements: [time, ax1, ay1, ..., gz3]
    """
    matlab_dir = os.path.join(script_dir, '..', 'matlab')

    gt_path = os.path.join(matlab_dir, 'ground_truth.csv')
    imu_path = os.path.join(matlab_dir, 'synthetic_imu.csv')

    # Check files exist
    if not os.path.exists(gt_path):
        print(f"ERROR: Ground truth file not found at:")
        print(f"  {os.path.abspath(gt_path)}")
        print(f"\nPlease run the MATLAB data generation script first.")
        print(f"Expected location: {os.path.abspath(matlab_dir)}/")
        sys.exit(1)

    if not os.path.exists(imu_path):
        print(f"ERROR: Synthetic IMU file not found at:")
        print(f"  {os.path.abspath(imu_path)}")
        print(f"\nPlease run the MATLAB data generation script first.")
        sys.exit(1)

    # Load CSV files (skip header row if present)
    try:
        gt_data = np.loadtxt(gt_path, delimiter=',', skiprows=1)
    except ValueError:
        # Try without skipping rows (no header)
        gt_data = np.loadtxt(gt_path, delimiter=',')

    try:
        imu_data = np.loadtxt(imu_path, delimiter=',', skiprows=1)
    except ValueError:
        imu_data = np.loadtxt(imu_path, delimiter=',')

    print(f"Loaded ground truth:  {gt_data.shape[0]} samples × {gt_data.shape[1]} columns")
    print(f"Loaded synthetic IMU: {imu_data.shape[0]} samples × {imu_data.shape[1]} columns")

    return gt_data, imu_data


def initialize_ukf():
    """Create and initialize the UKF with appropriate parameters.

    Returns
    -------
    ukf : UKF
        Fully initialized UKF ready for processing.
    """
    n_state = 13  # [q0,q1,q2,q3, wx,wy,wz, ax,ay,az, bx,by,bz]
    n_meas = 18   # 3 IMUs × (3 accel + 3 gyro)

    # ── Initial state: body at rest, upright orientation ──
    x0 = np.zeros(n_state)
    x0[0] = 1.0  # identity quaternion (no rotation)

    # ── Initial covariance ──
    # Reflects our uncertainty in the initial state
    P0_diag = np.array([
        1e-4, 1e-4, 1e-4, 1e-4,   # quaternion: fairly confident
        0.1, 0.1, 0.1,              # angular velocity: moderate uncertainty
        0.1, 0.1, 0.1,              # angular acceleration: moderate uncertainty
        0.1, 0.1, 0.1               # gyro bias: moderate uncertainty
    ])
    P0 = np.diag(P0_diag)

    # ── Process noise covariance Q ──
    # Models how much the state can change randomly per timestep.
    # Tuning these values is critical for filter performance.
    Q_diag = np.array([
        1e-6, 1e-6, 1e-6, 1e-6,    # quaternion: very small (constrained)
        1e-4, 1e-4, 1e-4,           # angular velocity: moderate
        1e-2, 1e-2, 1e-2,           # angular acceleration: larger (can change fast)
        1e-8, 1e-8, 1e-8            # gyro bias: very small (changes slowly)
    ])
    Q = np.diag(Q_diag)

    # ── Measurement noise covariance R ──
    # Based on MPU6050 datasheet noise specifications.
    # Format: [accel×3, gyro×3] repeated for each IMU
    R_diag = np.zeros(n_meas)
    for i in range(3):  # 3 IMUs
        R_diag[i*6 : i*6 + 3] = SIGMA_ACCEL**2   # accelerometer variance
        R_diag[i*6 + 3 : i*6 + 6] = SIGMA_GYRO**2  # gyroscope variance
    R = np.diag(R_diag)

    # ── Create UKF instance ──
    ukf_filter = UKF(
        n_state, n_meas,
        process_model, measurement_model,
        Q, R,
        alpha=UKF_ALPHA, beta=UKF_BETA, kappa=UKF_KAPPA
    )
    ukf_filter.x = x0.copy()
    ukf_filter.P = P0.copy()

    return ukf_filter


def run_filter(ukf_filter, imu_data):
    """Run the UKF over all timesteps.

    Parameters
    ----------
    ukf_filter : UKF
        Initialized UKF instance.
    imu_data : ndarray, shape (N, 19)
        IMU data: [time, ax1, ay1, ..., gz3]

    Returns
    -------
    est_euler : ndarray, shape (N, 3)
        Estimated Euler angles [yaw, pitch, roll] in radians.
    est_omega : ndarray, shape (N, 3)
        Estimated angular velocity [wx, wy, wz] in rad/s.
    est_quat : ndarray, shape (N, 4)
        Estimated quaternions.
    est_bias : ndarray, shape (N, 3)
        Estimated gyro bias.
    """
    N = imu_data.shape[0]

    # Storage arrays
    est_euler = np.zeros((N, 3))
    est_omega = np.zeros((N, 3))
    est_quat = np.zeros((N, 4))
    est_bias = np.zeros((N, 3))
    nis_hist = np.zeros(N)
    P_hist = np.zeros((N, 13, 13))

    print(f"\nRunning UKF over {N} timesteps...")
    start_time = time.time()

    for k in range(N):
        # Extract measurement vector (columns 1:19, skip time column)
        z = imu_data[k, 1:]  # 18 values

        # ── Predict step ──
        ukf_filter.predict(DT)

        # ── Update step ──
        nis = ukf_filter.update(z)

        # ── Store estimates ──
        est_quat[k] = ukf_filter.x[0:4]
        est_omega[k] = ukf_filter.x[4:7]
        est_bias[k] = ukf_filter.x[10:13]
        est_euler[k] = quat_to_euler(ukf_filter.x[0:4])
        nis_hist[k] = nis
        P_hist[k] = ukf_filter.P.copy()

        # Progress indicator (every 10%)
        if (k + 1) % (N // 10) == 0:
            pct = 100 * (k + 1) / N
            elapsed = time.time() - start_time
            print(f"  {pct:5.1f}% complete ({k+1}/{N}) — {elapsed:.1f}s elapsed")

    elapsed = time.time() - start_time
    print(f"UKF completed in {elapsed:.2f} seconds ({N/elapsed:.0f} Hz)")

    return est_euler, est_omega, est_quat, est_bias, nis_hist, P_hist


def compute_gt_euler(gt_data):
    """Convert ground truth quaternions to Euler angles.

    Parameters
    ----------
    gt_data : ndarray
        Ground truth: [time, q0, q1, q2, q3, wx, wy, wz, ax, ay, az]

    Returns
    -------
    gt_euler : ndarray, shape (N, 3)
        Ground truth Euler angles [yaw, pitch, roll] in radians.
    gt_omega : ndarray, shape (N, 3)
        Ground truth angular velocity [wx, wy, wz].
    time_vec : ndarray, shape (N,)
        Time vector in seconds.
    """
    N = gt_data.shape[0]
    time_vec = gt_data[:, 0]
    gt_euler = np.zeros((N, 3))

    for k in range(N):
        q = gt_data[k, 1:5]  # [q0, q1, q2, q3]
        gt_euler[k] = quat_to_euler(q)

    gt_omega = gt_data[:, 5:8]  # [wx, wy, wz]

    return gt_euler, gt_omega, time_vec


def create_plots(time_vec, gt_euler, est_euler, gt_omega, est_omega, save_path):
    """Create a publication-quality 4-subplot comparison figure.

    Parameters
    ----------
    time_vec : ndarray
        Time vector in seconds.
    gt_euler : ndarray, shape (N, 3)
        Ground truth [yaw, pitch, roll] in radians.
    est_euler : ndarray, shape (N, 3)
        Estimated [yaw, pitch, roll] in radians.
    gt_omega : ndarray, shape (N, 3)
        Ground truth angular velocity.
    est_omega : ndarray, shape (N, 3)
        Estimated angular velocity.
    save_path : str
        Path to save the figure.
    """
    # Convert to degrees for plotting
    gt_deg = np.degrees(gt_euler)
    est_deg = np.degrees(est_euler)
    error_deg = est_deg - gt_deg

    # Wrap angle errors to [-180, 180]
    error_deg = (error_deg + 180) % 360 - 180

    # Compute RMSE for each angle
    rmse = np.sqrt(np.mean(error_deg**2, axis=0))
    angle_names = ['Yaw', 'Pitch', 'Roll']
    angle_indices = [0, 1, 2]  # yaw, pitch, roll in our convention

    # Color palette
    colors = {
        'yaw':   '#e74c3c',   # red
        'pitch': '#2ecc71',   # green
        'roll':  '#3498db',   # blue
    }
    color_list = [colors['yaw'], colors['pitch'], colors['roll']]

    # ── Create figure ──
    fig, axes = plt.subplots(2, 2, figsize=(14, 10))
    fig.suptitle('UKF Multi-IMU Sensor Fusion — Offline Validation',
                 fontsize=14, fontweight='bold', y=0.98)

    # ── Subplot 1: Euler Angles ──
    ax1 = axes[0, 0]
    for i, (name, color) in enumerate(zip(angle_names, color_list)):
        ax1.plot(time_vec, gt_deg[:, i], color=color, linewidth=1.5,
                 label=f'{name} (truth)', alpha=0.7)
        ax1.plot(time_vec, est_deg[:, i], color=color, linewidth=1.0,
                 linestyle='--', label=f'{name} (UKF)', alpha=0.9)
    ax1.set_xlabel('Time (s)')
    ax1.set_ylabel('Angle (°)')
    ax1.set_title('Euler Angles: Ground Truth vs UKF Estimate')
    ax1.legend(loc='upper right', ncol=2, fontsize=7)
    ax1.grid(True, alpha=0.3)

    # ── Subplot 2: Angular Velocity ──
    ax2 = axes[0, 1]
    omega_labels = ['ωx', 'ωy', 'ωz']
    for i, (label, color) in enumerate(zip(omega_labels, color_list)):
        ax2.plot(time_vec, gt_omega[:, i], color=color, linewidth=1.5,
                 label=f'{label} (truth)', alpha=0.7)
        ax2.plot(time_vec, est_omega[:, i], color=color, linewidth=1.0,
                 linestyle='--', label=f'{label} (UKF)', alpha=0.9)
    ax2.set_xlabel('Time (s)')
    ax2.set_ylabel('Angular Velocity (rad/s)')
    ax2.set_title('Angular Velocity: Ground Truth vs UKF Estimate')
    ax2.legend(loc='upper right', ncol=2, fontsize=7)
    ax2.grid(True, alpha=0.3)

    # ── Subplot 3: Estimation Error ──
    ax3 = axes[1, 0]
    for i, (name, color) in enumerate(zip(angle_names, color_list)):
        ax3.plot(time_vec, error_deg[:, i], color=color, linewidth=0.8,
                 label=f'{name}', alpha=0.8)
    ax3.axhline(y=0, color='gray', linewidth=0.5, linestyle='-')
    ax3.set_xlabel('Time (s)')
    ax3.set_ylabel('Error (°)')
    ax3.set_title('Euler Angle Estimation Error')
    ax3.legend(loc='upper right', fontsize=8)
    ax3.grid(True, alpha=0.3)

    # ── Subplot 4: RMSE Bar Chart ──
    ax4 = axes[1, 1]
    bar_positions = np.arange(len(angle_names))
    bars = ax4.bar(bar_positions, rmse, color=color_list, width=0.5,
                   edgecolor='white', linewidth=1.5, alpha=0.85)

    # Add value labels on top of each bar
    for bar, val in zip(bars, rmse):
        height = bar.get_height()
        ax4.text(bar.get_x() + bar.get_width() / 2., height + 0.01,
                 f'{val:.4f}°', ha='center', va='bottom', fontsize=10,
                 fontweight='bold')

    ax4.set_xticks(bar_positions)
    ax4.set_xticklabels(angle_names, fontsize=11)
    ax4.set_ylabel('RMSE (°)')
    ax4.set_title('Root Mean Square Error by Euler Angle')
    ax4.grid(True, alpha=0.3, axis='y')

    # ── Finalize ──
    plt.tight_layout(rect=[0, 0, 1, 0.96])
    plt.savefig(save_path, dpi=200, bbox_inches='tight',
                facecolor='white', edgecolor='none')
    print(f"\nFigure saved to: {os.path.abspath(save_path)}")

    plt.show()


def main():
    """Main entry point for offline UKF validation."""
    print("=" * 70)
    print("  UKF Multi-IMU Sensor Fusion — Offline Validation")
    print("=" * 70)

    # Set up
    script_dir = os.path.dirname(os.path.abspath(__file__))
    setup_plot_style()

    # Load data
    gt_data, imu_data = load_data(script_dir)

    # Verify data dimensions
    N_gt = gt_data.shape[0]
    N_imu = imu_data.shape[0]
    N = min(N_gt, N_imu)

    if N_gt != N_imu:
        print(f"WARNING: Ground truth ({N_gt}) and IMU ({N_imu}) have "
              f"different lengths. Using first {N} samples.")
        gt_data = gt_data[:N]
        imu_data = imu_data[:N]

    # Convert ground truth to Euler angles
    gt_euler, gt_omega, time_vec = compute_gt_euler(gt_data)

    # Initialize and run UKF
    ukf_filter = initialize_ukf()
    est_euler, est_omega, est_quat, est_bias, nis_hist, P_hist = run_filter(ukf_filter, imu_data)

    # Compute and print RMSE
    error_deg = np.degrees(est_euler - gt_euler)
    error_deg = (error_deg + 180) % 360 - 180  # wrap to [-180, 180]
    rmse = np.sqrt(np.mean(error_deg**2, axis=0))

    print("\n" + "=" * 50)
    print("  RMSE Results (degrees)")
    print("=" * 50)
    print(f"  Yaw   (psi):    {rmse[0]:.6f} deg")
    print(f"  Pitch (theta):  {rmse[1]:.6f} deg")
    print(f"  Roll  (phi):    {rmse[2]:.6f} deg")
    print(f"  Mean RMSE:      {np.mean(rmse):.6f} deg")
    print("=" * 50)

    # Print final estimated gyro bias
    print(f"\nEstimated gyro bias: [{est_bias[-1, 0]:.6f}, "
          f"{est_bias[-1, 1]:.6f}, {est_bias[-1, 2]:.6f}] rad/s")

    # Calculate NEES for Omega (angular velocity)
    # Omega is states 4,5,6
    nees_hist = np.zeros(N)
    for k in range(N):
        err = est_omega[k] - gt_omega[k]
        P_omega = P_hist[k, 4:7, 4:7]
        try:
            nees_hist[k] = err.T @ np.linalg.solve(P_omega, err)
        except:
            nees_hist[k] = 0

    # Create NIS/NEES plot
    fig, axes = plt.subplots(2, 1, figsize=(10, 8))
    axes[0].plot(time_vec, nis_hist, label='NIS')
    axes[0].axhline(18, color='r', linestyle='--', label='Expected (m=18)')
    axes[0].set_title('Normalized Innovation Squared (NIS)')
    axes[0].legend()
    axes[0].grid(True)
    
    axes[1].plot(time_vec, nees_hist, label='NEES (Omega)')
    axes[1].axhline(3, color='r', linestyle='--', label='Expected (n=3)')
    axes[1].set_title('Normalized Estimation Error Squared (NEES)')
    axes[1].legend()
    axes[1].grid(True)
    
    nis_path = os.path.join(script_dir, 'nees_nis.png')
    plt.tight_layout()
    plt.savefig(nis_path, dpi=150)

    # Create plots
    save_path = os.path.join(script_dir, 'results.png')
    create_plots(time_vec, gt_euler, est_euler, gt_omega, est_omega, save_path)

    print("\nDone! ✓")


if __name__ == '__main__':
    main()
